### ISSUE TITLE
Work on this

### ISSUE THREAD

**Issue by whippingdot** [RayhanADev/ReplFans#1]
Bruh actually work on this and don't leave the project after you finish. We NEED this!

P.S. If you can, make it so that if you follow that person, you will get updates whenever a new post is made by that person as default. You can have a notification customization for each person you follow, and you can choose to get notified on new posts or comments or both **or neither**

**Note: Bold things are an Edit**

**Comment by darkdarcool** [comment]
lol **WORK ON THIS**

**Comment by RayhanADev** [comment]
I am I am xD, I'm learning how to make chrome extension while I'm at this lol.

**Comment by darkdarcool** [comment]
Ah ok lol
